project:
  type: book
  output-dir: docs

book:
  title: "CASA0023 - Learning Diary"
  author: "Zhou Yingxi"
  date: "2025/3/28"
  navbar:
    logo: casa_logo.jpg     
    collapse: true                          
    search: true                            
  sidebar:
    style: floating                         
    reader-mode: true
  favicon: casa_logo.jpg
  repo-url: https://github.com/Yingxi-Z/RS_weeklyworkdairy  
  repo-actions: [edit, issue]                
  chapters:
    - index.qmd
    - 01_Get_start.qmd
    - 02_Xaringan.qmd
    - 03_RS data.qmd
    - 04_Policy.qmd
    - 05_GEE.qmd
    - 06_Classification_1.qmd
    - 07_Classification_2.qmd
    - 08_SAR.qmd

bibliography: references.bib

format:
  html:
    theme:
      light: [cosmo, flatly]    
      dark: [cosmo, darkly]     
    code-link: true 
    base-url: "/RS_weeklyworkdairy/RSbook/docs/"
  pdf:
    documentclass: scrbook      

