project:
  type: book

book:
  title: "RSbook"
  author: "Zhou Yingxi"
  date: "2025/3/11"
  chapters:
    - week1.qmd
    - week2.qmd
    - week3.qmd
    - week4.qmd
    - week5.qmd
    - week7.qmd

bibliography: references.bib

format:
  html:
    theme:
      - cosmo
      - brand
  pdf:
    documentclass: scrreprt

editor: visual

