project:
  type: book
  output-dir: docs

book:
  title: "CASA0023 - Learning Diary"
  author: "Zhou Yingxi"
  date: "2025/3/28"
  navbar:
    logo: docs/casa_logo.jpg      
    collapse: true                          
    search: true                            
  sidebar:
    style: floating                         
    reader-mode: true
  favicon: docs/casa_logo.jpg
  repo-url: https://github.com/Yingxi-Z/RS_weeklyworkdairy  
  repo-actions: [edit, issue]                
  chapters:
    - index.qmd
    - week2.qmd
    - week3.qmd
    - week4.qmd
    - week5.qmd
    - week6.qmd
    - week7.qmd
    - week8.qmd
    - week9.qmd

bibliography: references.bib

format:
  html:
    theme:
      light: [cosmo, flatly]    
      dark: [cosmo, darkly]     
    code-link: true             
  pdf:
    documentclass: scrbook      

