project:
  type: book
  output-dir: docs

book:
  title: "RSbook- learning dairy"
  author: "Zhou Yingxi"
  date: "2025/3/18"
  chapters:
    - index.qmd
    - week2.qmd
    - week3.qmd
    - week4.qmd
    - week5.qmd
    - week7.qmd
    - week8.qmd
    - week9.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme:
      - cosmo
      - brand

editor: visual

